### PR TITLE
adding code snippets

### PR DESCRIPTION
**Pull request by pstjohn**
Here's an option for showing some code snippets..

Not sure how I host the static site?

### CODE REVIEW

**Comment by cdiener** [comment]
Hi thanks. Not bad, maybe I would prefers something shorter. A small example is fine but larger code samples are probably left for the docs. Maybe just show how to load the model call optimize and maybe a shortened summary output?

Also could you separate that from the styles changes, because I would like to discuss them separately, for instance: 

- I think the grid should stay a bit wider, otherwise the Packages section looks weird. Usually one aims for close to full width on older laptops (1366px wide).
- The zero padding on `highlight` [does not look good on mobile](https://cloud.githubusercontent.com/assets/7153935/22070544/047ac8b8-dd62-11e6-832d-6e65df78ffb0.png)
- [justified text has some problems](http://designforhackers.com/blog/never-justify-type-on-the-web/)

Cheers and thanks.

**Comment by pstjohn** [comment]
No worries! My first attempt with hugo :)
Agreed on the length, figured I could err on the side of too much and cut down.
I'll try playing around a bit with getting it to work with the current styling.

**Comment by pstjohn** [comment]
Let me know if this is ok?
I edited the margin on #hero, since otherwise there's a lot of whitespace between the logo and the next line.

I also bumped the highlight max-width to 700px to give a bit more room for the text. Let me know fi you want me to bump that back to 600px.

**Comment by cdiener** [comment]
Yeah, that looks good. The code is a bit cut off on mobile but we can play around with that in the following weeks. There are also several themes for Prism. Okaidia or coy could look good as well.

Thanks!

**Pull request merged**
